### ISSUE TITLE
Folder cannot be uploaded

### ISSUE THREAD

**Issue by StanZzz11** [stevedylandev/pinata-go-cli#3]
Environment: Windows 11
Command: pinata.exe upload ./folder

Result:
Uploading folder (11.35 MB)
Uploading... 100% |████████████████████████████████████████| (3.0 MB/s)
Upload complete, pinning...
2024/01/04 10:36:36 server Returned an error 400

**Comment by stevedylandev** [comment]
Hey @BTCZzzzzz! Thanks for the heads up. Can you confirm if it's working for an individual file instead of a folder? I'll see what I can do to help patch this but might be tricky since I don't have a windows system to test and debug. 

Another option you could consider is using WSL2 and using the Linux binary instead

**Comment by StanZzz11** [comment]
@stevedylandev Yes, I confirmed that files can be uploaded in Windows, but if you upload a folder, error code 400 will be returned.

Http Result: {"error":"More than one file and/or directory was provided for pinning."}

**Comment by StanZzz11** [comment]
@stevedylandev In WSL with Linux it works perfectly, In Windows it works when uploading a single file, but when uploading a folder it gets a 400

**Comment by stevedylandev** [comment]
Interesting, thanks for confirming that! I'll have to look into this further. I'm sure it has something to do with how Windows handles file paths and directories vs UNIX based systems.

**Comment by stevedylandev** [comment]
Unfortunately for the time being we will have to put this on backlog. We don't have the means to debug this on Windows but will be looking into setting up an env for future debugging and testing. In the meantime I will update the readme instructing Window users to take the WSL route instead.
